# Generated by Django 2.2 on 2020-08-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together={('match', 'player')},
        ),
    ]
